import { useState } from "react";
import "./StudyPlan.css";

const DAYS = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const COLORS = ["#7c6af7","#4ade80","#fb923c","#f472b6","#60a5fa","#34d399"];

export default function StudyPlan({ user, updateUser }) {
  const todayIdx = new Date().getDay();
  const todayKey = DAYS[todayIdx === 0 ? 6 : todayIdx - 1];
  const [activeDay, setActiveDay] = useState(todayKey);
  const [generating, setGenerating] = useState(false);
  const [aiPlan, setAiPlan]    = useState(null);
  const [doneTasks, setDoneTasks] = useState({});
  const [error, setError]      = useState(null);
  const [config, setConfig]    = useState({
    subjects: "Mathematics, Physics, Chemistry, Biology",
    examDate: user?.examDate || "",
    hours: String(user?.dailyHours || 4),
    goals: "",
  });

  const handleConfigChange = (patch) => {
    const updated = { ...config, ...patch };
    setConfig(updated);
    if (patch.examDate !== undefined && updateUser) updateUser({ examDate: patch.examDate });
  };

  const generatePlan = async () => {
    setGenerating(true);
    setError(null);
    setDoneTasks({});
    try {
      const token = localStorage.getItem("token") || "";
      const subjectList = config.subjects.split(",").map(s => s.trim()).filter(Boolean);
      const prompt = `Create a realistic 7-day study plan for a student.
Subjects: ${subjectList.join(", ")}
Daily study hours: ${config.hours}
Exam date: ${config.examDate || "in 3 weeks"}
${config.goals ? `Goals: ${config.goals}` : ""}

Return ONLY valid JSON with no markdown:
{"plan":{"Mon":[{"time":"9:00","subject":"Mathematics","topic":"Algebra Basics","duration":90,"color":"#7c6af7"}],"Tue":[],"Wed":[],"Thu":[],"Fri":[],"Sat":[],"Sun":[]}}`;

      const res = await fetch("/api/studyplan/generate", {
        method: "POST",
        headers: { "Content-Type":"application/json", "Authorization":`Bearer ${token}` },
        body: JSON.stringify({ userId: user?.id, prompt }),
      });

      let parsed;
      if (!res.ok) {
        parsed = buildStaticPlan(subjectList, Number(config.hours));
      } else {
        const text = await res.text();
        try {
          const match = text.match(/\{[\s\S]*\}/);
          parsed = JSON.parse(match ? match[0] : text);
        } catch {
          parsed = buildStaticPlan(subjectList, Number(config.hours));
        }
      }

      if (!parsed.plan) throw new Error("Invalid plan format");
      // Ensure colors exist on all tasks
      const coloredPlan = {};
      DAYS.forEach((d, di) => {
        coloredPlan[d] = (parsed.plan[d] || []).map((t, ti) => ({
          ...t,
          color: t.color || COLORS[(di + ti) % COLORS.length],
        }));
      });
      setAiPlan(coloredPlan);
    } catch (e) {
      const subjectList = config.subjects.split(",").map(s => s.trim()).filter(Boolean);
      const fallback = buildStaticPlan(subjectList, Number(config.hours));
      setAiPlan(fallback.plan);
      setError(null);
    }
    setGenerating(false);
  };

  const buildStaticPlan = (subjects, hours) => {
    const plan = {};
    const timeSlots = ["8:00","9:30","11:00","13:00","14:30","16:00","17:30","19:00"];
    DAYS.forEach((day, di) => {
      plan[day] = [];
      const count = Math.min(Math.floor(hours / 1.5), subjects.length, 4);
      for (let i = 0; i < count; i++) {
        const si = (di + i) % subjects.length;
        plan[day].push({
          time: timeSlots[i] || "9:00",
          subject: subjects[si],
          topic: `${subjects[si]} — Session ${i + 1}`,
          duration: 90,
          color: COLORS[si % COLORS.length],
        });
      }
    });
    return { plan };
  };

  const toggleDone = (day, idx) => {
    const key = `${day}-${idx}`;
    setDoneTasks(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const todayTasks  = (aiPlan && aiPlan[activeDay]) || [];
  const doneCount   = todayTasks.filter((_, i) => doneTasks[`${activeDay}-${i}`]).length;
  const totalMins   = todayTasks.reduce((a, t) => a + (t.duration || 60), 0);
  const totalDone   = Object.values(doneTasks).filter(Boolean).length;
  const totalTasks  = DAYS.reduce((a, d) => a + ((aiPlan?.[d] || []).length), 0);

  return (
    <div className="study-plan">
      <div className="page-header">
        <h1>📅 AI Study Planner</h1>
        <p>Your personalized 7-day study schedule, generated by AI</p>
      </div>

      <div className="plan-layout">
        <div className="plan-main">
          {!aiPlan ? (
            <div className="card" style={{ textAlign:"center", padding:"60px 40px" }}>
              <div style={{ fontSize:64, marginBottom:20 }}>📅</div>
              <h2 style={{ marginBottom:12 }}>No study plan yet</h2>
              <p style={{ color:"var(--text-secondary)", marginBottom:24 }}>
                Fill in your details on the right and click <strong>Generate Plan</strong>.
              </p>
            </div>
          ) : (
            <>
              {/* Weekly progress bar */}
              <div className="card" style={{ marginBottom:16 }}>
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:8 }}>
                  <span style={{ fontSize:13, fontWeight:600 }}>Weekly Progress</span>
                  <span style={{ fontSize:13, color:"var(--accent-green)", fontWeight:700 }}>
                    {totalDone}/{totalTasks} tasks done
                  </span>
                </div>
                <div className="progress-bar" style={{ height:8 }}>
                  <div className="progress-fill"
                    style={{ width:`${totalTasks > 0 ? (totalDone/totalTasks)*100 : 0}%`, transition:"width 0.4s" }} />
                </div>
              </div>

              <div className="day-selector">
                {DAYS.map(d => {
                  const tasks = aiPlan[d] || [];
                  const done  = tasks.filter((_, i) => doneTasks[`${d}-${i}`]).length;
                  return (
                    <button key={d} className={`day-btn ${activeDay === d ? "active" : ""} ${d === todayKey ? "today" : ""}`}
                      onClick={() => setActiveDay(d)}>
                      <div className="day-label">{d}{d === todayKey ? " ·" : ""}</div>
                      <div className="day-dot-wrap">
                        {tasks.slice(0, 3).map((t, i) => (
                          <div key={i} className="day-dot"
                            style={{ background: doneTasks[`${d}-${i}`] ? "#4ade80" : t.color }} />
                        ))}
                      </div>
                      {tasks.length > 0 && (
                        <div style={{ fontSize:10, color:"var(--text-muted)", marginTop:2 }}>
                          {done}/{tasks.length}
                        </div>
                      )}
                    </button>
                  );
                })}
              </div>

              <div className="day-summary card">
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
                  <div>
                    <h2 style={{ fontSize:20 }}>{activeDay === todayKey ? "Today" : activeDay}</h2>
                    <p style={{ color:"var(--text-secondary)", fontSize:13 }}>
                      {todayTasks.length} sessions · {Math.floor(totalMins/60)}h {totalMins%60 > 0 ? `${totalMins%60}m` : ""}
                      {doneCount > 0 && ` · ${doneCount} done ✅`}
                    </p>
                  </div>
                  <div className="day-progress-circle">
                    <svg viewBox="0 0 60 60">
                      <circle cx="30" cy="30" r="24" fill="none" stroke="var(--border)" strokeWidth="5" />
                      <circle cx="30" cy="30" r="24" fill="none" stroke="var(--accent-primary)" strokeWidth="5"
                        strokeDasharray={`${2*Math.PI*24}`}
                        strokeDashoffset={`${2*Math.PI*24*(1-(todayTasks.length ? doneCount/todayTasks.length : 0))}`}
                        transform="rotate(-90 30 30)" strokeLinecap="round" />
                      <text x="30" y="35" textAnchor="middle" fill="var(--text-primary)" fontSize="13" fontWeight="800">
                        {todayTasks.length ? Math.round(doneCount/todayTasks.length*100) : 0}%
                      </text>
                    </svg>
                  </div>
                </div>
              </div>

              <div className="tasks-list">
                {todayTasks.length === 0 ? (
                  <div className="card" style={{ textAlign:"center", padding:40, color:"var(--text-muted)" }}>
                    🎉 Rest day! No sessions scheduled.
                  </div>
                ) : todayTasks.map((task, i) => {
                  const isDone = doneTasks[`${activeDay}-${i}`];
                  return (
                    <div key={i} className={`task-card card ${isDone ? "task-done" : ""}`}
                      style={{ opacity: isDone ? 0.7 : 1 }}>
                      <div className="task-timeline">
                        <div className="task-time">{task.time}</div>
                        <div className="task-line" style={{ background: task.color }} />
                      </div>
                      <div className="task-body" style={{ borderLeft:`3px solid ${task.color}` }}>
                        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start" }}>
                          <div>
                            <div className="task-subject" style={{ textDecoration: isDone ? "line-through" : "none" }}>
                              {task.subject}
                            </div>
                            <div className="task-topic">{task.topic}</div>
                          </div>
                          <div style={{ display:"flex", gap:8, alignItems:"center" }}>
                            <span className="badge badge-purple">{task.duration || 60}min</span>
                            <button
                              style={{ background: isDone ? "#4ade80" : "rgba(124,106,247,0.1)",
                                border:`1px solid ${isDone ? "#4ade80" : "var(--border)"}`,
                                borderRadius:6, padding:"4px 10px", cursor:"pointer",
                                fontSize:12, fontWeight:600,
                                color: isDone ? "#000" : "var(--text-secondary)" }}
                              onClick={() => toggleDone(activeDay, i)}>
                              {isDone ? "✓ Done" : "Mark Done"}
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </>
          )}
        </div>

        <div className="plan-sidebar">
          <div className="card generate-card">
            <h3 style={{ marginBottom:6 }}>✨ Generate Study Plan</h3>
            <p style={{ color:"var(--text-secondary)", fontSize:13, marginBottom:16 }}>
              Powered by Groq AI — free & fast
            </p>
            {error && <div className="error-banner" style={{ marginBottom:12 }}>{error}</div>}
            <div style={{ display:"flex", flexDirection:"column", gap:12 }}>
              <div className="form-group">
                <label>Subjects (comma separated)</label>
                <input value={config.subjects}
                  onChange={e => handleConfigChange({ subjects: e.target.value })}
                  placeholder="Math, Physics..." />
              </div>
              <div className="form-group">
                <label>Exam Date</label>
                <input type="date" value={config.examDate}
                  onChange={e => handleConfigChange({ examDate: e.target.value })} />
              </div>
              <div className="form-group">
                <label>Daily Hours: {config.hours}h</label>
                <input type="range" min="2" max="12" value={config.hours}
                  onChange={e => setConfig({ ...config, hours: e.target.value })}
                  style={{ padding:0 }} />
              </div>
              <div className="form-group">
                <label>Goals (optional)</label>
                <input value={config.goals}
                  onChange={e => setConfig({ ...config, goals: e.target.value })}
                  placeholder="e.g. Focus on weak topics, practice problems..." />
              </div>
              <button className="btn btn-primary" style={{ width:"100%", justifyContent:"center" }}
                onClick={generatePlan} disabled={generating}>
                {generating ? "Generating..." : "✨ Generate Plan"}
              </button>
              {aiPlan && (
                <button className="btn btn-secondary" style={{ width:"100%", justifyContent:"center", fontSize:13 }}
                  onClick={() => { setAiPlan(null); setDoneTasks({}); }}>
                  🔄 Reset Plan
                </button>
              )}
            </div>
          </div>

          {aiPlan && (
            <div className="card">
              <h3 style={{ marginBottom:16 }}>📊 Weekly Overview</h3>
              {DAYS.map(d => {
                const tasks = aiPlan[d] || [];
                const mins  = tasks.reduce((a, t) => a + (t.duration || 60), 0);
                const done  = tasks.filter((_, i) => doneTasks[`${d}-${i}`]).length;
                return (
                  <div key={d} style={{ display:"flex", alignItems:"center", gap:10, marginBottom:10 }}>
                    <div style={{ width:32, fontSize:13,
                      color: d === todayKey ? "var(--accent-primary)" : "var(--text-muted)",
                      fontWeight: d === todayKey ? 700 : 400 }}>{d}</div>
                    <div className="progress-bar" style={{ flex:1 }}>
                      <div className="progress-fill"
                        style={{ width:`${Math.min((mins/300)*100, 100)}%` }} />
                    </div>
                    <div style={{ fontSize:12, color:"var(--text-secondary)", width:60, textAlign:"right" }}>
                      {done}/{tasks.length} · {Math.floor(mins/60)}h
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
